### ISSUE TITLE
Can't open offline skill tree

### ISSUE THREAD

**Issue by AvocadoCake** [EmmittJ/PoESkillTree#102]
There seems to be a bug in my "PersistentData.xml" file as when it's in the folder of the exe the program crashes when I try to open it, whereas when I take it out the program works fine. Both the xml and debug.txt can be downloaded here: https://www.mediafire.com/folder/1pmjywfwv5mt7/Error

**Comment by nastynyan** [comment]
This should work. 
https://drive.google.com/file/d/0B-ktjUGcKZUmTzZVYzZQOW5LdVk/view?usp=sharing

By some reason there was no closing tags after a note text. Seems it crashes in the middle of saving file. 
Could you elaborate what symbols you've been trying to put into the note? (it's starting with "Maligaro's, LC, Atziri's")

**Comment by AvocadoCake** [comment]
That's very strange, it's a build I haven't touched in months and I use the
offline tree almost every day, so it's that it started acting up now. I
don't remember what the sybols would have been but I can't imagine it would
have been anything other than a link/basic symbols (?, +, brackets, etc) I
use in other build notes.

**Comment by EmmittJ** [comment]
It looks like, from the debug file, that the app wasn't able to fully write to the file for some unknown reason. Which really doesn't make sense because there isn't anything else that should be writing or reading to it. Could have been an improper shutdown of the application (was killed before completely finishing write to file at close). 

Symbols shouldn't matter unless you were writting xml within the note.

**Comment by AvocadoCake** [comment]
Oh that makes sense, I thought some builds were missing, I guess it cut
some of them off. I had a count-down to turn off my computer at some point,
I guess the app didn't react too well to that.

**Comment by EmmittJ** [comment]
No apps really have a good response to being terminated without closure. Some are just designed to die more gracefully, which is what I will probably throw in. I did it with a couple of other things like data updating. Just store a temp file then overwrite if all went well

**Comment by l0g0sys** [comment]
I did some testing on Note content, and you can write there anything 
(XML reserved chars, non-printable chars) and it's properly serialized.
Just there is issue with non-printable characters during deserialization 
(it crashes during read on &#x1; for instance), but that's another issue.

The exception in debug.txt about not being able to access file is due to 
race condition during shutdown+crash. As shutdown wants to save data, 
then it crashes and crash handler wants to save data as well.

**Comment by EmmittJ** [comment]
Alright, I am not at a computer to test things but that makes sense.
Confirms my speculation about the shutdown condition as well as the note
thing (and probably any of the fields).
