### ISSUE TITLE
Full tree optimizer

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#106]
The original reason why I started looking into this project and worked on #98 was the vision of a tool that builds an entire tree based on specified user criteria.

There's so many tradeoffs (life, mana, damage, cast speed, mitigation etc.) that need to be made when devising a tree, and so many different nodes and node values (with widely varying point investments) that it's hard for a player to create something optimized. Only very few people actually do/check the math. For example, it's generally worth to take the melding cluster (25% ES) over spending those four points in the scion ES wheel (24% after you got Foresight), even if you only care about ES.
Or another example, I often wonder whether I should get more cast speed or rather more spell damage in my tree at a particular point in order to optimize my dps. That obviously depends on my gear and my current tree, but that's data that can already be fed to the existing skill tree tool.

It's only a matter of letting the user communicate his desires and priorities about the tree. Well, "only" doesn't really nail it, the required UI work (and thought) is the entire challenge here.
My current idea is that users can select a node (control-click? Or go into a special mode and right click?) and then choose how much he values certain attributes that node has (which will "apply" to all nodes with those attributes).
Going one step further, either the user should be able to combine attributes (dpsMulti = (1+spelldmg)*(1+castspeed)) or there should premade functions that compute things of interest (total life, armor...). In particular, Compute.cs (I was really impressed somebody sat down and basically recreated the engine!) will provide accurate calculations for whatever setups and gem links people want.
Then there needs to be a way for the user to weight those aspects in a certain way. Here my idea is that the user selects a desired target value and how important it is to reach that value. A Mjölner char has pretty set requirements for str and int (so that would have full priority), but maybe setting desired life to 160% increased and giving it lower priority could give you 150% life with much better dps. You get the point.

Interestingly enough, all the "hard" algorithmic work is already completed with #98: Instead of searching for the set of steiner points with the lowest point investment, all nodes possibly affecting the user defined tree value will be part of the searched node combinations. The genetic algorithm doesn't really care, it only needs a fitness function (providing which will be the challenge). It's obviously going to take longer to find the optimum, but that's a given.

I still don't really know how to represent "value" for this, and how the individual aspects should be combined (multiplied? added?). And especially how to make this somewhat transparent for a user.

So these are the questions I'm asking myself at the moment:
-In what way should the scores for e.g. life and dps be defined, and how should those be combined into a final score/(fitness) value?
-How fast is Compute.cs? Is it modifiable in a way that permits faster calculations when only some/a few of the input things change?
-Most of all: How should the UI for this be built so that it is both powerful but also accessible to an unfamiliar user (who has no idea of math)?

I'm keen to hear your thoughts on this!

**Comment by EmmittJ** [comment]
The thing about an optimizer, and you know this, is that weights are going to be different every single time you skill a node. I would say start off by calculating its efficiency based on how far and the value on the node.
Not sure if that makes sense so example:
One life node 5% is 10 away and another life node 8% is 15 away the 8% node would technically be more efficient. You may have to calculate how many nodes you can branch off of a single line.

**Comment by MLanghof** [comment]
I know that, and I also know that that problem is already solved.

The current algorithm (from #98) is, at its core, a genetic algorithm. It explores a solution space (in this case, a set of nodes to skill), asking a fitness function (in that case, the amount of points invested) to evaluate the "value" of any particular solution. The optimizing algorithm knows literally nothing about the tree! It just (sort of) randomly walks around in the space of all possible solutions (skilled nodes) and tries to find the one that yields the highest value of the fitness function.

For a complete tree optimizer, all you have to do is build a different fitness function that evaluates a given tree. It doesn't matter if some nodes have different values or different distances.
The GA will select a set of nodes and query the fitness function for how good that solution is. The fitness function can then calculate that e.g. that particular tree gives you a life total of 4000 and maybe 7000 dps, which is combined into a single rating ("value", "fitness", whatever you want to call it). Then the GA will try to find better solutions by exploring the vicinity of that solution (if it was decent compared to the others).

The approach is not per-node already. It already evaluates an entire tree at once. Currently it only measures the point investment, but virtually anything (like the number of letters in the node names... or the colors of the pixels in its graphic, it doesn't matter) could be used as the measure that the GA is asked to optimize.
So really, the challenge is to let the user communicate what he wants.

**Comment by MLanghof** [comment]
Well, things will get slightly more interesting with #108...

**Comment by brather1ng** [comment]
Actually, this is also the reason I looked into this project (although you did the algorithm work far better than I would have been able to).

My take on the rating would be basically a split in two parts, hard and soft constraints. Hard constraints would be stuff like maximum of 110 points spent, a total of 4000 health or Acrobatics keystone included. Those things need to be met for a skill tree to be decently rated.
Then the soft contstraints would influence the rating itself, it would calculate a dps multiplier, a defense-ratio and a utility-ratio that includes everything else and combine these with some weighting into one score. For the influence of certain values the user would be able to weight certain attributes, for example he doesn't want accuracy to be part of the dps-multiplier at all, so that would get a weight of 0, but crit chance to be weighted double, so that would get a 2.
The way all this gets calculated together could be defined by letting the user set a build, that can be optionally automatically generated by the users imported items. For example the main skill, weapon type used, if he wants to go crit or not, what types of defense should be utilized and things like that. This would be probably get very complex pretty easily to account for every case.
A first implementation of the UI to even see if all this is feasible at all would not include all the build and gear things.
With generating most things through imported items and defining preset configurations, this would not get too complex to understand for the user, but with all the things that can influence the optimal skill tree, I doubt there is a non-complex, very easy to understand solution.

Also, here is a really quick non-functional mockup of what I imagined as the UI (obviously not complete, the right side should probably be put into tabs/extra windows, since it would include far more settings).
![generatorsettings](https://cloud.githubusercontent.com/assets/7596346/8467102/60092a74-205a-11e5-87ec-dbeff23b305c.png)

Regarding jewels: depending on how they will be supported by the planner, either give the optimizer a list of jewels which he picks the best for the available sockets of, or add a setting for how many nodes a jewel socket is worth to the user.

**Comment by MLanghof** [comment]
Haha, I'm really glad I'm not the only one out there who sees the potential in this :D

> Also, here is a really quick non-functional mockup of what I imagined as the UI
This is already a pretty detailed one. Aspects that I think are already good are the "defense/offense" slider, the ability to load gear, choose bandits and active buffs, as well as being able to save builds.

As far as I'm aware, there's already a fully functional Compute.cs that can handle almost all skill/support gem combinations, including damage conversions and whatnot. It will also calculate total life etc. iirc. We might be able to make use of that and let the user actually specify what he wants to use ingame (items, links). While we could still have presets so users could get started with something, I don't really like the idea of making the creation of new builds more painful than it needs to be.

About the constraints: I too think that there needs to be a distinction in the priority of these, but it's important to keep in mind that the fitness function for the GA won't look nice if you give builds 0 score for not hitting all hard constraints.
What I'd suggest would be a simple priority slider, while the "fulfillment" of the constraint is converted into an exponentially (or polynomially) growing stat, scaled by the priority.

The question still remains how to combine these into one fitness function value: Is having twice the health but half the movespeed as good as having the precise health and movespeed? In other words, do you multiply the constraint satisfaction values? Add them? Something else?

Here's an example of how I imagine it could work (without any thought about if it would actually work out in practice, but just so we have something to start from): All constraint satisfaction values (I'll call it csv) range from 0 to 1 and get multiplied with each other.
Say you have the constraint "total life" set to 4000 and maximum priority. There's also "critical strike chance (your weapon)" as a constraint at 300%, but at half priority. Finally there's a constraint about "increased movement speed" at minimum priority, set at 20%.

The csv for life will look something like [this](http://www.wolframalpha.com/input/?i=plot+exp%2810+x%2F4000%29+%2F+exp%2810%29+from+0+to+4000) (can't get W|A to scale axes right, mind the y scaling). The csv for crit might look like [this](http://www.wolframalpha.com/input/?i=plot+exp%283+x%2F300%29+%2F+exp%283%29+from+0+to+300), while the csv for movespeed would probably look like [this](http://www.wolframalpha.com/input/?i=plot+exp%281+x%2F300%29+%2F+exp%281%29+from+0+to+300).

Note that this does not yet handle the case where you exceed a constraint target! That would need to be handled in a different manner (and I suppose there are stats for which diminishing returns are harsher than for others: If you're crit capped then exceeding the constraint target should not increase the csv any higher (as in, the user needs to be able to prevent that from happening), but having more life is virtually always welcome.

**Comment by brather1ng** [comment]
>As far as I'm aware, there's already a fully functional Compute.cs that can handle almost all skill/support gem combinations (I think totems are still not in), including damage conversions and whatnot. It will also calculate total life etc. iirc. We might be able to make use of that and let the user actually specify what he wants to use ingame (items, links). While we could still have presets so users could get started with something, I don't really like the idea of making the creation of new builds more painful than it needs to be.

Yeah, I did not intend to recreate all those calculations.
Being able to specify the build on the item level does sound better than all the different parameters I threw into the mockup. Also with #117 this might be really intuitive to do if you have the option to either import the gear or create it with the item editor. One thing that should be kept in mind is that not everyone has the gear he would like to use or even knows how it would look like, so some gear-independent way should be included.

>About the constraints: [..]

If you would give everything a target value and a priority slider, the user would need to be able to specify a target value. For example you might know that you value crit chance above accuracy, but that doesn't mean you know any kind of target value for those.
For the fitness function I imagined something like the hard constraints making up the upper half of the bits and the soft constraints the lower half, so something with better hard constraints is always better than something with worse, but there is still some room for the GA to make selections.

Another idea would be to multiply the hard constraints together as with your example and use that as a multiplier for the (soft-constraints-based) rest of the fitness function. That would at least be a starting point as you said.

However for constraints that do not have a target value (the soft constraints in this case), would need to be scaled differently.
My idea is to have basically three different values, the first is a dps multiplier (as it is calculatetable by Compute.cs I assume), the second is a value for all defense related things (maybe calculate effective hp in some way?) and then everything else like leech, movement speed as a combined third value (these could for example be simply added together). Each constraint that gets calculated into one of the three value would get multiplier by the user given weight before being combined.
Then the question would be how to combine the three values, this would somehow include the defense/offense-slider.

**Comment by MLanghof** [comment]
> If you would give everything a target value and a priority slider, the user would need to be able to specify a target value.

I can't make sense of that sentence, but I assume you mean what the following sentence explains (somehow value constraints without a target value). Note that this could be kinda iffy, since the app doesn't know anything about the relative worth of stuff. What if you add a life constraint with high priority but no value? Does that mean a tree with 4000 life is rated twice as high as a 2000 one? Or only as a 3000 one? I have trouble putting this on a mathematically sound basis (and you'll notice that new players have this same issue with the tree, we simply have experience to tell us. The question is if we want to give the app "experience").

> I imagined something like the hard constraints making up the upper half of the bits and the soft constraints the lower half

I... don't really know what you mean. The bits encode not the fitness function value but the individuals. In other words, the priorities have no influence on the individual representations. I mean, if you want to build the fitness function values bitwise you *could* do that, but that's equivalent to just weighting each constraint with a (different) power of 2.

Using a uniform formula (as in, not split it into 3 parts) for the fitness function has the advantage that you get predictable results: Adding together csvs and then multiplying them can lead to unexpected (not in the programming sense) behavior, where you can e.g. double a fitness with marginal investment because you added a small value to another small value.

On a related note, if you let the user explicitly specify a target health, total eva/armor etc. while also letting him value dps with constraints, the offence/defence slider loses its meaning. I guess we have to choose here.

**Comment by brather1ng** [comment]
>I can't make sense of that sentence, but I assume you mean what the following sentence explains (somehow value constraints without a target value).

Yes, I mean constraints without a target value, since for many things the user would not really know what a good target value would be, so the optimizer would have to compare things in a relative way. With your life example my idea would basically multiply the value the tree has for a stat with the constraint value, so the value itself for 4000 life would be rated twice as high as 2000 life.

>> I imagined something like the hard constraints making up the upper half of the bits and the soft constraints the lower half

>I... don't really know what you mean.

I meant in the result of the fitness function. Lets say the fitness is an integer and you have the hard and soft constraint ratings as a short. To combine them, you would put the hard constraint rating in the upper bits of the result and the soft constraints in the lower bits. Could have been worded better.

The split into 3 parts formula would only include ratings for soft constraints, so specified target health and evasion would not influence that.

But I will fiddle around with it later and see if the stuff I'm saying does make any sense.

**Comment by MLanghof** [comment]
>  To combine them, you would put the hard constraint rating in the upper bits of the result and the soft constraints in the lower bits

Hm so you did mean that, I wasn't sure. Again though, this is simply adding them with weights. It would also mean that the soft constraints have *0* impact on which solution is better if the hard constraint ratings differ.

**Comment by brather1ng** [comment]
Yeah, using the hard constraints as a factor is probably better.

>And yeah, I edit my stuff a lot after posting.

Lol, good that I randomly stumbled upon this sentence and read the comment again. :D

>Keep in mind that using this tool for lower levels also makes sense (think LLD or leveling), and it gets really hard if you want to work without user-supplied constraint target values.

Hm, why would it be harder to work without target values on lower levels?

Just an idea to throw in here: A useful feature for leveling trees would be something like only searching in a given subtree (which would be the endgame tree).

>I suppose you could do an "autopilot" mode [...], while also having an "advanced" mode

Yeah, that sounds awesome :)

But idk, specifiying target values for everything that is taken into consideration sounds pretty hard on the user part, at least for specific values like % increased damage and things like that. This would probably only have a use on a more abstract level with things like total health, total evasion, dps on the main skill, etc. (which should be possible to calculate with Compute.cs). And also as you said it would be more useful as an advanced mode, since a relatively inexperienced user would not know what dps to shoot for, for example.

I guess the best thing to do is to start with different fitness function approaches and throw out the ones that prove to not be very useful. In the end the remaining ones could then be used for the user to select between (named like "autopilot", "advanced", ...).

**Comment by l0g0sys** [comment]
For me, it would be totaly enough if full tree optimizer in initial release would have just one button "Optimize" and it could just take my current tree and find "better" one.

If you have tree A with attributes A1..An, then tree B is "better", if it contains all attributes A1..An and their values are same or higher then in tree A, while total used points in tree B is lower than total used points in tree A. Of course, tree B must contain all keystones of tree A.

Simply, don't lower my attributes but try to reduce used points. Then i can decide on my own what to do with those extra points.

Later, in far away future, it could compare computed values from Compute.cs instead of attribute values. But it's not possible atm, due to missing calculations for leeching (life/mana), mana regeneration, mana consuption (skill mana cost, mana reservation) and lot more. You cannot optimize tree disregarding these calculations.

**Comment by l0g0sys** [comment]
After looking at that UI for optimizer... i don't think it's needed at all :)

Heuristic can be used to determine features of build (tree + equipment).
So you don't need to specify that you are using Split Arrow when we already have that information from equipment.
There is no need to specify critical chance, attack speed and rest of DPS affecting values, if we can calculate DPS and process of DPS optimization is actually to find best combination for all these offensive attributes while raising the DPS.
There is no need to specify which defense types are used. It's determinable from equipment and tree.
And so on.

**Comment by MLanghof** [comment]
You are requiring people to actually have made a tree so they can use the full optimizer. I would like to be free of all "prejudice" when giving input to the optimizer, and no matter how you build your tree, you'll always end up with a confused/misinterpreting optimizer ("oh no, I didn't get 14 flat energy shield, let's scrap this beautiful tree").

If we implement your "optimize button" idea, we would end up with an optimizer that can already optimize based on (extremely rigid) constraints. It would actually be a waste to not let the user choose what he wants directly instead of the "make a tree and try to avoid very specific things" (think 30% stun avoidance, 8% status ailment avoidance, 30% reduced enemy critical strike multi etc.). It's also a lot *harder* to make the optimizer work with that "all or nothing" approach: If you tell him that every tree that doesn't have *all* constraints has 0 score, it will never be able to approach an optimum.

This is also why i proposed the exponential scaling approach for the csv earlier: You give the optimizer a hint of progress, but the biggest score increase happens when you reach the target value.

**Comment by l0g0sys** [comment]
Well, optimizing tree is what i expect from tree optimizer :) Not build wizard. I don't want optimizer to play game for me. I have good tree and i want to make it better. That all or nothing was just an example of different approach. If it's not possible then it's ok. Reduction of nodes used is way to optimize tree too. Each extra point saved is actually improvement. You just don't have to specify beforehand into which direction (i.e. which stat you want to improve with those free points).

If i want to make tree from scratch i can already do it now. I can tag nodes i want and just skill them :)
So all those "i want this at X" and "that at Y" constraints would save bit of simple math and few clicks as opposite to current "skill nodes" implementation with manual node selection.

At the end of day, i'm worried how useful it would be with those "constraint this and that". Because, whatever solution will be found, there can be multiple better solutions if i swapped only 1 item in build before running it.

But why not, someone might use it. Just thinking out loud :)

**Comment by brather1ng** [comment]
Optimizer here is probably not the best word, what we discussed is more a generator (that solves an optimization problem).
But there really isn't much difference in the end. If one is done, the other is simple a matter of changing the start configuration (between starting from an empty or a given tree).

The thing with your suggestion is, if the optimizer would only produce trees that have exactly the same stats (or better), there would not be much too optimize, because one tree statistic configuration is pretty unique.
What you implicitly assuming is that things like base stat travelling nodes for example are not relevant, but that is knowledge the optimizer would need to have. Also if you have specific things like 30% stun avoidance, how would the optimizer know if that is relevant to tree or can be skipped?
From the point of telling the optimizer what kind of stats are relevant you pretty easily get to fully constrainting the stats, so you are at the point where we currently are, just with a different start configuration and an emphasize on less points spent, which both are not hard to do.

So as you can see, there really isn't much difference between starting from scratch or from a given tree. The difference between optimizing and generating a tree is probably even smaller than that between generating a tree and the current "skill node" way. It isn't simple math that would be done by the algorithm, most people that make skill trees don't do the math if for example 4% attack speed or 10% physical damage is better in the current situation.

>But why not, someone might use it. Just thinking out loud :)

Honestly, I don't have any idea if people would use something like this. But I am interested in coding it, so that is enough for me :)

**Comment by l0g0sys** [comment]
> Optimizer here is probably not the best word, what we discussed is more a generator (that solves an optimization problem).

Yeah, i already noticed that it isn't what i thought it would be :) Maybe issue should be renamed to "Skill tree generator" or wizard to not give people false hopes :p

> What you implicitly assuming is that things like base stat travelling nodes for example are not relevant, but that is knowledge the optimizer would need to have.

Yep, it should have this knowledge. As i mentioned earlier. If lowering base stat doesn't break item/gem requirement (which we don't care about for now), then value of base stat node is implicitly just "less you travel better it is".

> Also if you have specific things like 30% stun avoidance, how would the optimizer know if that is relevant to tree or can be skipped?

I think that's the main problem. Why should it skip in first place? I think the base premise, that existing tree is wrong is incorrect. All stats in my existing tree are relevant to me.
But in this particular example, bit of thinking tells me, that if maximum value of stun avoidaince is 100% and node gives 30% of those 100%. Then this node might be way more relevant than 5% maximum Life node from let's say 140% maximum Life from all allocated tree nodes.
Well, this is the real challenge of tree optimization :) So you either create such ranking algorithms or just shift it to user.

> It isn't simple math that would be done by the algorithm, most people that make skill trees don't do the math if for example 4% attack speed or 10% physical damage is better in the current situation.

Then what's the point of asking people to enter such constaints in your optimizer settgins UI? :) The question "is 4% attack speed better than 10% phys damage?" should be solved by optimizer.
In this example, there is simple way to rank their value. You just have to use computed stat like DPS to compare their impact.

**Comment by brather1ng** [comment]
Something that might not be clear enough: Doing it constraint based does not necessarily mean that the user would see those constraints (see the "automated" mode above). They are internally needed to have a proper way of comparing trees.

>Yeah, i already noticed that it isn't what i thought it would be :) Maybe issue should be renamed to "Skill tree generator" or wizard to not give people false hopes :p

Well, I don't think it gives false hopes because they are very similar and implementing both is not much overhead over only implementing one.

>I think that's the main problem. Why should it skip in first place? I think the base premise, that existing tree is wrong is incorrect. All stats in my existing tree are relevant to me.

No, not all stats in your existing tree are relevant to you. Say for example you picked up "Master of the arena" notable at Duelist start, but you are a bow build. The optimizer would be locked onto that node because it is the only one that has the stat "+# to Melee Weapon and Unarmed range" (that is completely irrelevant to you), so every tree that does not have that node, has to be discarded.
One could argue the same way about stun avoidance if you have stun immunity for example trough Unwavering Stance.

>Well, this is the real challenge of tree optimization :) So you either create such ranking algorithms or just shift it to user.

Yes, that challenge is exactly what we were discussing previously :)

>Then what's the point of asking people to enter such constaints in your optimizer settgins UI? :) The question "is 4% attack speed better than 10% phys damage?" should be solved by optimizer.
In this example, there is simple way to rank their value. You just have to use computed stat like DPS to compare their impact.

As I did write above, those constraints, especially in this case, would be done implicitly by the optimizer. The reason I wrote it, was to show that a tree generator is not just the "Skill node" feature plus "simple math".

**Comment by MLanghof** [comment]
From what I can tell, brather1ng have quite the same idea with where can (and want to) take this.

l0g0sys, For your application of "make my tree better" you can already simply select all nodes that are relevant to you and do the "Skill highlighted nodes" as it is currently ("Reduction of nodes used is way to optimize tree too. Each extra point saved is actually improvement." -> That's precisely what I would use the current version for). I understand that you would maybe also want the tree to consider different life clusters, but that's exactly where we get to what we actually want to implement: You tell the optimizer what you *actually* want instead of letting it guess.

>  The question "is 4% attack speed better than 10% phys damage?" should be solved by optimizer.

You seem to have misunderstood: That's *exactly* what the optimizer would do for you, it's not "simple math" as you said earlier ("...would save bit of simple math and few clicks"). That's why we want to let the optimizer build entire trees from scratch with a certain itemset in mind, because computers are good at figuring this stuff out, while brains get easily biased by stuff.

> there can be multiple better solutions if i swapped only 1 item in build before running it.

This is a very good and valid point. It would probably be worthwhile to somehow output a set of trees (maybe with a certain minimum difference between them, you don't need 3 otherwise identical trees that have insignificant pathing differences). Like, the best tree is shown but you have a list of alternatives to check.

**Comment by brather1ng** [comment]
I have done some basic work on this. Once I have the basic class structure done (without any real new functionality), which will hopefully be in a few days, I'll push it to a branch in my fork.
I can give MLanghof and anyone else that wants to help with it write access there then.

**Comment by brather1ng** [comment]
The initial class structure is now done (see my treeGen branch).
If @MLanghof or someone else wants to help me with the implementation, I'll give you write access to my fork and I guess it is better to move most of the discussion there to keep this somewhat clean.
If not, you'll hear from me once I have something done that is worth showing off :)

**Comment by MLanghof** [comment]
So how's your progress @brather1ng? I think I might have the time now to progress this further :)

**Comment by brather1ng** [comment]
I have not done anything the last week, but am currently working on it again.

A very basic "AdvancedSolver" is nearly done (with only the basic attribute constraints), I only need to link the GUI to the Solver. That should hopefully be finished today.

For a todo/idea list, see TreeGenerator.ViewModels.AdvancedTabViewModel in my treeGen branch. The first three is what I want to finish for a first, maybe somewhat useful, Tree Generator.
The CreateSolver method there is what it does atm if you run the generator with the Advanced tab open (Tools -> Nodes -> Skill Tree Generator), the Tagged Nodes tab does the same thing as Skill Tagged Nodes and the Automated tab doesn't do anything (well it does something, it crashes the program ;) ).

**Comment by brather1ng** [comment]
That very basic Solver is working now. Not with acceptable results, but at least working :D

I guess if you want to help it's best to organize the stuff a bit more than my basic list, so we should probably move the discussion and todos to issues in my fork. So feel free to open an issue there for whatever you decide to start working on. I am done for today, so you can pick up on anything atm :)

**Comment by brather1ng** [comment]
If someone someday plans on going further with the tree generator, it's probably better to discuss that in a new issue anyway. On my todo list it's so far back that it has a good chance that I'll never get to it.

**Comment by EmmittJ** [comment]
I would agree, this is a bit old and some information might be outdated. Closed.
