### ISSUE TITLE
Full Tree Optimizer/Skill Highlighted Nodes not getting ideal path

### ISSUE THREAD

**Issue by teuneboon** [EmmittJ/PoESkillTree#114]
I was playing with the "Skill Highlighted Nodes" function, it didn't get the ideal path for me:
![Example 1](http://i.imgur.com/IbfYwrL.jpg)
Why did it go through those 2 minion nodes while it could also have gone through just 1 crit node?

Full tree:
![Example 2](http://i.imgur.com/LTxpLtr.jpg)
Already fixed the mistake in this screenshot

**Comment by MLanghof** [comment]
Thanks for this info. To be open about it, the optimizer is not technically _guaranteed_ to find the best solution, only *very likely* (because the task is "very difficult" from a mathematical perspective, *guaranteeing* an optimal solution would take a very long time).

I'll check out your example and see what I can do to tweak things.

Thanks for the report!

**Comment by MLanghof** [comment]
After looking into this, you seem to have gotten somewhat unlucky (with your configuration, I got that result only very few times upon letting it run multiple times), but I opted to tweak something so the optimizer should be more robust (and yeah, this means it'll take longer, tradeoffs everywhere).

Thanks again for reporting this! I tried hard to come up with "difficult" inputs before, but there's always new ones that I need to watch out for. Please do inform me if you get a bad result again!

**Comment by EmmittJ** [comment]
I can close this if you wish. It seems like you may have fixed the problem?

**Comment by EmmittJ** [comment]
I guess 'problem' it will never be 100% :p

**Comment by MLanghof** [comment]
Indeed, there's only so many different trees I can check in a given amount of time. And lots of common inputs have many orders of magnitude more possible tree solution candidates than that.

I can influence the balance between "can accept a worse candidate in order to move away from an *almost* optimal solution" and "pursue an almost optimal solution and optimize it as far as possible", but ultimately there's always "easy" and "hard" inputs.

You can close this issue if you want, but I'll still have to push the tweak. I guess I need to open a pull request every time for that?

**Comment by EmmittJ** [comment]
Correct. Just like everyone else :)
