### ISSUE TITLE
Multiple groups Regex

### ISSUE THREAD

**Issue by cezelkowitz** [EmmittJ/PoESkillTree#125]
Cannot search for... example:
(Phys)+ (Elem)+

Single groupings work, but not multiple. The skill tree crashes when typing the second parenthesis. My best guess is that the code isn't written to handle a second (or more) grouping.

Will fix myself once I get GitHub working...

**Comment by l0g0sys** [comment]
This is already fixed in #111.
Tho not released yet.

**Comment by EmmittJ** [comment]
Yep, was fixed.

**Comment by cezelkowitz** [comment]
Gotcha. Looked like it just had to be switched to Matches vs Match for
groupings. But idk.

**Comment by EmmittJ** [comment]
Well the regex is handled by C#. There isn't any special logic that we
built in.
On May 23, 2015 1:21 PM, "cezelkowitz" <notifications@github.com> wrote:

Gotcha. Looked like it just had to be switched to Matches vs Match for
groupings. But idk.

On Sat, May 23, 2015 at 12:31 PM, Emmitt Johnson <notifications@github.com>
wrote:

> Yep, was fixed.

>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmmittJ/PoESkillTree/issues/125#issuecomment-104922845
>

> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/125#issuecomment-104941451>.

**Comment by cezelkowitz** [comment]
Yeah. Match returns you a single result, Matches returns you a collection
of results. I'm more of a Java guy but that was my first take on it from
when it failed to apply the regex groupings. My presumption was that a
String.split was required on either spaces to handle any groupings or on
open/close braces (, [, {, to apply specific groupings, use Matches instead
of Match, and then iterate over the collection returned.

Anyway, thanks for the fix. Can't wait to see it out there so I can search
for Elemental damage + Phys damage + Life at same time and more easily
search for quickest routes. Maybe in a later version you can impement
Dykstra's to a set of wanted nodes and find the shortest route while
favoring specific nodes such as Ele/Phys/Life :D... That might be overkill
:)

**Comment by EmmittJ** [comment]
It is already implemented and in the tools sections called skill
highlighted nodes. It uses steiners tree problem though which solves for
the smallest tree. You can read more about it if you look through the
closed issues

**Comment by l0g0sys** [comment]
You can search for multiple things at once using RegEx right now, just have to write correct expression ;)

You look at RegEx groups wrong way. Groups are not for matching multiple things, but to provide more complex expressions.
The thing that RegEx engine can return matched groups is just a feature for programmer to save his time.

You can look at RegEx groups as parenthesized subexpressions in Java or C/C#, like this:
```Java
if ((A) && (B)) { /*...*/ }
...
if ((A) || (B)) { /*...*/ }
```
See? "if" statement cannot behave based on "groups" A and B, it has to behave based on expression as whole. Because only whole expression puts both "groups" into relation.
It's same with RegEx. Application cannot match based on groups, as those don't have meaning when separated from the whole, so it has to match against whole expression.

So, if you want to search for Elemental damage + Physical damage + Life. You can write it like this:
```
Elem.+ Damage|Phys.+ Damage|maximum Life
```
or this:
```
(Elem.+|Phys.+) Damage|maximum Life
```

The expression you wrote, has it's own meaning too. Schematically you wrote this:
```
(A) (B)
```
which means match group A followed by space, which is followed by group B.

Hope this will make RegEx groups more clearer for you :)
