### ISSUE TITLE
New feature on hover over an unallocated node

### ISSUE THREAD

**Issue by gophren** [EmmittJ/PoESkillTree#133]
When hovering over an unallocated node, if you press Alt (or any other defined key) replace the tooltip of the current hovered node with the reunion of all the tooltips of the nodes from the shortest path to this unallocated node.
If there are several shortest path, choose one at random.

**Comment by SpaceOgre** [comment]
I'm not completely sold on this idea. If it is only a few nodes then the info could fit nicely in a tooltip window, but if you are highlighting 20+ nodes or so there might be way to much text to display in a good way in a tooltip.

What do the rest of you think?

**Comment by l0g0sys** [comment]
Well, the whole suggested functionality is quite disputable.

When using current algorithm to show path on hover, which is and must be fast, and as such far from optimal, most of the time you would just see attributes like +Strength and such.
So, this kind of information would have almost no value in most cases.

The only few cases when this information would have any value, would be while hovering over 
very close nodes with very short paths. That would sort of help with summing few numbers instead of using your head :)

Maybe if we put some limit on path length? That would raise the chance of having useful information and also would limit number of attributes being displayed.

Path with more than X nodes would display with Alt “Too long path to display summary”.
If path is shorter than X nodes, it would display “Attribute summary: and below list of summed attributes on highlighted path).

Note: btw. won't be Alt interfering with Alt system command focusing main menu?

**Comment by EmmittJ** [comment]
Correct, alt would be focusing the main menu. The shift modifier is
normally pretty good for things like this, since it doesn't have anything
to do.

**Comment by EmmittJ** [comment]
I don't think this idea will make it through. There isn't much of a use case and hasn't been talked about in almost a year. I will go ahead and close this.
