### ISSUE TITLE
Skill node highlighting ambiguity

### ISSUE THREAD

**Issue by l0g0sys** [EmmittJ/PoESkillTree#149]
There is ambiguity in node highlighting when right-clicking the attribute name in Attributes sidebar and right-clicking a node in Skill tree.

It is confusing to have green and blue circle highlighting with same meaning, but different way of access. Not to mention that you can have green circle with red cross together on same node.

Is it possible to have just one type of highlighting for node inclusion?

Using only green circle (easier to spot than blue one) should be sufficient.
For attribute name clicking to act as "all or nothing" toggle as it's current behaviour, the check for existance of corresponding highlighted node should be done first.
If such node exists, then unhighlight all highlighted corresponding nodes.
If no such node exists, then highlight all corresponding nodes.

**Comment by MLanghof** [comment]
Uh, my intention was to have RGB coding for the different ways. As in, right click node = blue, right click attribute = adds green (now turqiose), right click node again = remove blue (now green).

I mean, my primary intention with this method would've been that you can right click your life attribute in the list, therefore see all life nodes, then manually (blue) highlight the ones you want, then remove the attribute-based highlights.

With your suggestion (at least how I understand it) rightclicking the wrong attribute could result in having half your manual highlights erased (because you probably don't want to find a tree that encompasses *all* life nodes).

**Comment by l0g0sys** [comment]
There are so many ways to screw stuff within a split of second, if you do something you should not :)

I understand it, you understand it. Question is, if rest of common folks will understand it.
I won't be the one writing manual explaining all those color combinations :p
Hope color blind people won't have trouble with it.

If you think that this protection is worth of raised complexity. I'm fine with it.

**Comment by brather1ng** [comment]
Another thing here is that it might not even be screwing up stuff by mistake.
For example you manually highlight some notable that has life for also having life regen, then you attribute highlight all life nodes to see what you could also highlight (with your suggestion you actually need to rightlick attributes twice, first the notable will be erased). After that you unhighlight that attribute again.
Well your manual highlight is now gone, you'd need to remember everything you previously highlighted to be able to restore it after another type of highlight overlaps with it.

Since search also has another highlight color, I think it would not be too difficult too understand that different ways of highlighting have different colors. You don't need to actually remember which color comes from which combination imo.

**Comment by l0g0sys** [comment]
Think i found where i wasn't clear enough and got carried away.

I think optimizer should ignore yellow and also red circles. Those should be only informational.
You search for node, you find it and then you decide what to do with it manually. Only blue circles should be the ones used by optimizer.

Just right-click "maximum Mana" attribute or type "life" into search box. Good luck running optimizer with all those nodes :)

I think It should work like this:
1) search (attribute name clicking, search box, other sources)
2) decide (select for optimizer)
3) run optimizer

**Comment by l0g0sys** [comment]
Think adding cross sign gave us good opportunity to make clear distinction between types of highlighting. As it's hard to call it as form of highlighting.

For the purpose of optimizer term "tag" sould be introduced. Blue circle should be replaced with green checked sign (like in checkbox input). Both green checked symbyl and red cross symbol should be called "tags".

Thus process of highlighting the nodes (placing a colored circle) would be purely result of search methods (clicking on attribute name, typing text into seach box).

While process of tagging would be result of decision whether found (highlighted) nodes should be considered by optimizer to either included them (checked) or exclude them (crossed).

New menu item "Remove All Tags" could be added to clear all node tags, while Unhighlight nodes would clear only highligting (colored circles) resulted from search.

This would make completely clear distinction between highliting as searching for nodes and tagging  as marking the nodes with tags for purpose of optimization.

**Comment by brather1ng** [comment]
That sounds way better. I like that idea.

Also with an additional menu entry like "Check-tag all highlighted nodes" (and maybe also "Cross-tag all highlighted nodes") for the cases where it would make sense, there won't be any functionality lost compared to what it is now.

**Comment by MLanghof** [comment]
I too like the idea of separating highlighting stuff from using it for the optimizer. It might also help with #106.

I was initially thinking about letting the full tree optimizer UI be accessed by choosing constraints based on nodes (or attributes) you click in a particular manner (e.g. Ctrl + RMB). This would be doable with the proposed distinction (or even use an exclamation mark instead of the check mark), but I'm not sure if it's user friendly enough. Having *one* UI for the full optimizer might be better in the end.

The question still remains if there should be an interaction between nodes and full optimizer.

**Comment by brather1ng** [comment]
For the skill highlighted nodes thing some kind of highlighting/tagging is obviously necessary. So I would say it would not hurt to have the option to also use it for the full optimizer, at least for the highlighting/tagging currently in place. It could also be made accessible in the settings UI, so it could be done in both (updating each other).

Changing constraints like you thought of could then also be done as an *additional* way to the settings UI if ithat feels intuitive.

**Comment by brather1ng** [comment]
Since it seems like no one has started this yet, I'll start working on this later today (and will probably finish it, doesn't look like much work).
The menu entry icons need to be done by someone else though.

**Comment by EmmittJ** [comment]
Might want to hold off until I get the jewel stuff merged. I am waiting on
the item editor guy to merge all of his stuff too
