### ISSUE TITLE
Crafting windows - Uniques

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#157]
Unique's  should be selectable in the crafting window

**Comment by Iztooi** [comment]
I don't want to necro-post, but creating another issue when there was already one open might not be good.
Is there some news about this feature? I see that unique items are perfectly imported with no flaws, but is there a way to create uniques with the crafting window? I'm asking because it's the only tool out there that let you see how much perfection rating an item has (% of the stats compared to the maximum amount that item can roll), but uniques can have an unique affix or different ranges.

**Comment by brather1ng** [comment]
Posting here is fine.

It's still not possible to craft uniques. However, I'm somewhat working towards it atm. So, depending on how much time I have, it might be done in the near future.
