### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Propsyn** [EmmittJ/PoESkillTree#188]
Here is the debug i cant open it anyway. Is it me or something is wrong with it?

http://pastebin.com/SDhpMn3H

Edit Comment: Added the debug.txt to pastbin since it was so long

**Comment by brather1ng** [comment]
This is an issue that only appears with some languages. See #182.

It is fixed but not yet released. While it is not released, you can use the installer @EmmittJ linked in the bottom of comment thread:
https://drive.google.com/file/d/0B2BWKeD5Id_gbE9SWURLVzFqRzQ/view?usp=sharing

Since it seems more people are having this issue, a bug fix release would be useful imo.

**Comment by EmmittJ** [comment]
Yep, I will make a pre-release in just a few minutes.

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/releases/tag/2.2.2

Here is the 'official' release

**Comment by Propsyn** [comment]
Thank you mate you are awesome! It is working very well. Thanks for every work you do :)

**Comment by EmmittJ** [comment]
Alright, good work everyone lol closing this :)
