### ISSUE TITLE
New Build Saving Structure

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#192]
I would like to open up a discussion about possibly a new build saving format that doesn't keep them all in one file. 

I believe persistent data should be thing related to settings for the app (maybe a rename), and we have a completely different setup for builds.

I suggested that we do a folder set up but as @l0g0sys pointed out there are a couple problems with this structure:
1) Naming: Build name would have to be separate information from file name. Unless build name would be more strict about allowed characters to make 1:1 build name to file name mapping. And question is what role subfolders would be playing in build naming.
2) Sorting: There wouldn't be any manual sorting, maybe just automatic sorting based on name or creation/modification time. Using some toggle buttons.
3) Filtering/Searching: This would require to traverse folder structures and parse each build file to filter based on character class or search in notes. Unless whole structure of build files would be read on launch and kept in memory during runtime.

**Comment by SpaceOgre** [comment]
A folder structure would be good, since it will give flexibility for future additions that we don't want to keep in the same file.

1. Create a method that cleans the character name and use that for file name, or create a unique id so that two builds can have the same name or add a sort number. Save the real file in one of the files in the folder.
2. Just add a number too the folder and we have manual sorting. This would of course require us to rename all the affected folders when sorting is done, but that should not be to hard.
3. I think it would be best to read all builds at start and only write changes when needed.

**Comment by l0g0sys** [comment]
So, you want to use folders and keep current Saved build UI? I think those 2 things contradicts eachselves.

If we want to keep current UI (browse all builds in flat list), then we don't have to bother with folders at all. Just store build in separate file in one flat folder structure and that's it.
Sorting index for actual build files could be still serialized in PersistenData.xml as simple List&lt;string&gt; with file names as items. On launch, when new build file is discovered just push its file name to end of list and non-existing file name just remove from list.

Or, we can go with full document oriented model, like MS Office documents. That would mean full user control on folder structures and build file creation. Even managed outside of application in any OS/3rd party file browser.

**Comment by SpaceOgre** [comment]
True it is contradicting.

Have thought a bit more one the folder structure and if we want to go that route we need to decide what we want to show. Do we want a tree view like in explorer and visual studio? or something else. I feel like most if the info that is there in the current UI should be there in the new one as well: name, class and points at least.

**Comment by EmmittJ** [comment]
I think a tree view like visual studio would be the best. It allows a lot
of control over the build list as well as keeping a simple professional
look.

We will have to clean/truncate build names to fit within the specs of the
file system, but that shouldn't be too hard to return them, as long as they
aren't super long.

**Comment by SpaceOgre** [comment]
What are your feelings about a dirty state check when switching/creating a new build and showing a warning that changes have been made and will be discarded unless saved. Most editors have this but I'm thinking it might be a bit annoying for some users. 

We could ofc add an option to suppress these kind of messages in the settings window.

**Comment by EmmittJ** [comment]
Hmm, if they didn't save it they could always Ctrl + Z their way back, but
it could be a nice addition for those who need it.
I have never had a build I didn't save, so Idk.

**Comment by SpaceOgre** [comment]
True, but Ctrl+z only reverts the skill tree right? But there are a loot of other things that can be edited in a build: level, name, note, custom attribute groups etc

**Comment by EmmittJ** [comment]
Ah true! I think a state checker would be nice on build switch then

**Comment by SpaceOgre** [comment]
Since discussions about this have resurfaced I have done some thinking and have the following thoughts/questions:
**New format/GUI**
* The information available at glance today include Name, Points and Class. We need to decide what we want to show in the new layout.
* What functionality do we want to support? I feel like these are mandatory for a ease of use:
 * Create/Delete folder
 * Move/Drag build from one folder to another
 * Rename build and folder
 * Limit folder/build placement to the save folder
* As I see it it would be good to emulate visual studios solution explorer to give a good overview and possibility to easily move a build from one folder to another. On the other hand a with a layout like this it might be hard to show the information we show today, for this we could add a "properties" window just like in visual studio.
* Should filename and buildname be the same? If yes buildnames will have limitations. (I think they should be the same)
* Read new build files on the fly. This would be nice and should be possible with some sort of filelistener.
**Move builds from old to new**
Unless we ship this change of save structure together with a tree change that makes old builds non loadable, we need to migrate saves from the old structure to the new. For this I see the following challenges: 
* If we choose to use filename = buildname, buildnames need to be cleaned and maybe shortened.
* Today we have no limitation on buildname uniqueness, with the new a build name need to at least be unique in its folder. During migration check for duplicate names and add a number last to make it unique.

These are just brainstorming points, feel free to shoot them down or discuss other ideas :)

**Comment by l0g0sys** [comment]
Some time ago was thinking too about navigation in build folder structure. As you mentioned, using classical TreeView would require to change how stuff is displayed completely.

But then I thought about something like mobile devices use nowadays to navigate through menu tree.

Folder would be displayed same way our build is displayed today as ListViewItem, just with arrow to right. When such "folder" item is clicked, the ListView slides to left revealing content of folder as new ListView with top item labeled Back with arrow to left. When Back item is clicked, it slides back to parent ListView.

To get an idea, see http://mmenu.frebsite.nl/ and play with left side menu.

Though, this might require some XAML templating maybe new controls and stuff... like using MahApps.Metro TransitioningContentControl or maybe there is something like this already done.

**Comment by brather1ng** [comment]
I would prefer TreeView over the sliding menu thing mainly for two reasons:

1. TreeView shows more information (builds) at once. 
2. Moving a build from one folder to another is much easier to do intuitively in TreeView because Drag/Drop easily works for that.

Also, I don't think there is big difference in how much work is required to get them to work. The underlying data structure should be same and they would only differ in XAML stuff.

> On the other hand a with a layout like this it might be hard to show the information we show today, for this we could add a "properties" window just like in visual studio.

I haven't looked into TreeView specifically but it should be possible to simply change the item template to show all the information we want to show.

> Should filename and buildname be the same? If yes buildnames will have limitations. (I think they should be the same)

These limitations could partially be solved by encoding/decoding the buildnames with something like `HttpUtility.UrlEncoded` (or a self written encoder as url encoding does more than necessary).

I do want to start splitting up/refactoring our MainWindow code anyway, so I may start with the builds stuff and get some prototypes together over the next few days.

**Comment by l0g0sys** [comment]
Yeah, each way has it's pros/cons.

Tho, i'm not fan of drag/drop at all, ctrl+c/x/v all the way when 
possible :)

Regarding encoding filenames, that's good idea. Actually, you suggested 
the most safe method using URL encoding :)

I doubt it's worth the time to spend on making own encoder/decoder which 
would be doing pretty much same thing the URL encoding does.

Lot of stuff to take into consideration like file name encoding in 
different filesystems (FAT, NTFS, extX, ...), special characters in 
different OS's or even locale settings.

**Comment by SpaceOgre** [comment]
> Tho, i'm not fan of drag/drop at all, ctrl+c/x/v all the way when
possible :)
I think we should aim to support both.

> I haven't looked into TreeView specifically but it should be possible to simply change the item template to show all the information we want to show.

Absolutely. My concern is that it might either make to GUI to big (lots of horizontal scroll) or that the text have to made so small that it is hard to read. But can't know for sure until implemented and tried out. These might be unwarranted concerns but would rather lift it now so that we can check it :)

> These limitations could partially be solved by encoding/decoding the buildnames with something like `HttpUtility.UrlEncoded` (or a self written encoder as url encoding does more than necessary).

This seems like a great idea.

**Comment by brather1ng** [comment]
TreeView prototype:

![hierarchicalbuilds](https://cloud.githubusercontent.com/assets/7596346/16351806/c455a5ce-3a68-11e6-80ad-740a3977f8a1.PNG)

This prototype wasn't much work at all so I think going with TreeView is much easier than implementing the sliding menu thing.

**Comment by MLanghof** [comment]
Looks nice! Really looking forward to it :)

**Comment by SpaceOgre** [comment]
Yeah,  looks good!

**Comment by brather1ng** [comment]
A few more thoughts and ideas:

1. We could give the folders more information than just a name. Things like account name and league could be specified in folders and inherited by builds in these if they are not specified there directly (the information would still need to be stored in build files because those should be independentyl shareable). The biggest problem here is to come up with a good UI to make clear what is inherited and what isn't.
2. These build files are meant to be shareable, so I don't think the AppData folder is a good place for them. What about the user's Documents folder? For portable installation it should stay in the installation folder.
3. We could give the build files a custom file extension (`.pbuild`?) and bind that to the program through Windows. Together with the point above and a menu link to open the build folder, this would be enough for a Import/Export system mentioned by @SpaceOgre above, imo.
4. I would like to tie the current build and the build in the build list it came from together. The current build could then be directly changed in the build edit menu without needing to reload it. New builds not yet saved would be the only ones that have no representation in the build list. This would include checking dirty states and mentioning unsaved changes to the user.

**Comment by SpaceOgre** [comment]
> We could give the folders more information than just a name. Things like account name and league could be specified in folders and inherited by builds in these if they are not specified there directly (the information would still need to be stored in build files because those should be independentyl shareable). The biggest problem here is to come up with a good UI to make clear what is inherited and what isn't.

Not sure about this, I think it might be more intuitive if it was possible to just change these things for many builds at once. This could be done by adding support to select many builds or on a folder basis.

> These build files are meant to be shareable, so I don't think the AppData folder is a good place for them. What about the user's Documents folder? For portable installation it should stay in the installation folder.

I guess this is down to preference? Because I hate that apps/games put stuff in the Documents folder instead of in their own. And if you go for _a menu link to open the build folder_ I don't think it would be necessary to change it.

Totally agree with 3 and 4.

**Comment by l0g0sys** [comment]
I agree with Daniel.

Regarding Documents folder and file association of build files. I don't 
care. But I'm not gonna mess with build files directly, using Windows 
explorer or other file manager at all. Too much hassle.

And it's conflicting with your folder data inheritance. Don't think you 
can have both ways. Standalone build files you want to copy here/there 
outside of app and also to have some inheritable folder data.

**Comment by brather1ng** [comment]
Yeah, the inheritance stuff would conflict with a lot of things. It probably doesn't have enough benefits for it to be worth it. I like @SpaceOgre's idea of some kind of "edit all contained builds at once" for folders.

> And if you go for "a menu link to open the build folder" I don't think it would be necessary to change it.

True

**Comment by MLanghof** [comment]
This sounds like something that should be set by an installer.
I'm all for having a central build folder that the app uses. I concur though that having it hardcoded in the app is bad if the user is supposed to be able to access it easily for files.

So what about asking the user for a "build folder" path in the installer?

**Comment by l0g0sys** [comment]
Good you mentioned this, I almost forgot why we use AppData which is 
specific for each AppId defined in release.

In general, once we open file structure of build files to public (file 
associations/file manager access/centralized build folder/...), all sort 
of compatibility issues must be solved due to tree changes, item mod 
changes and other changes. If you want to support copying/using builds 
cross incompatible versions of applications you are asking for troubles :)

So before thinking about such stuff, maybe first handling of 
incompatible build files should be resolved (e.g. you copy/load 1.x 
build to/in 2.x release and such).

**Comment by brather1ng** [comment]
> So what about asking the user for a "build folder" path in the installer?

Good idea, I think that's the best solution. Though that will need a default value or an extra input dialog if the program is updated with the updater (I think, don't know much about our installer stuff).

> As for the folder structure, have you planned a maximum depth? I feel like one level sort of wastes the potential of folder organization, but the danger of program hangs (and UI issues) with unlimited folder nesting is also to be considered. I think three levels should cover virtually all use cases, allow reasonable assumptions for the UI design and also avoid most file system shenanigans.

Good points, didn't think about that yet.

On the compatibility issues:

I don't think that's a huge problem as I can't think of any similar incompatibilities happening with that until now. But it should be done to make that stuff future-proof.

An easy solution would be to store the current program version in build files, set the earliest compatible version in code and ignore/warn/whatever when incompatible builds are loaded.

**Comment by brather1ng** [comment]
I've implement the UI for the new build structure. You can check that out in the refactoring/builds branch (see commit 7a728de6878da243b0c62a945af28ba2b42aa102).

It has no integration with anything yet, so it's just UI stuff. Can be opened through Tools -> Unhighlight All Nodes (that's obviously only a temporary solution, will replace the current builds control with it once it is actually useable).

**Comment by BlazesRus** [comment]
Just keep links to standalone build files within PersistentData.xml.
Use an option flag to check if within the <PoEBuild> when scanning PersistantData for builds.
Such as if it finds <StandaloneBuildFile>BuildFile</StandaloneBuildFile>
For Standalone build saves, only save elements of <Name>,<StandaloneBuildFile>, <Class>, and <PointsUsed> within PersistantData.xml (for ease of displaying builds and so can just load the data needed to display build in list of builds).

**Comment by EmmittJ** [comment]
A file system type solution is being worked on currently.
