### ISSUE TITLE
Save Overwrites the Wrong Saved Build Index

### ISSUE THREAD

**Issue by dsnvwlmnt** [EmmittJ/PoESkillTree#217]
This bug has happened once too many times, i'm reporting it now.

I have a lot of saved builds (49 currently). I clicked Reset, made a build, and chose Save As and gave it a name. Made some more modifications, and then clicked Save. It overwrote the 2nd last build instead of the last one (the one i was editing). There is an issue with your index/selected build, where it becomes offset by -1.

**Comment by EmmittJ** [comment]
Save overwrites the build you have highlighted if I remember correctly.
This probably isn't the correct behavior, but that is what it does.

-1 should be correct in terms of how builds are stored and displayed. I
will double check to make sure that the selected index isn't -1 though.

**Comment by dsnvwlmnt** [comment]
Well, if the logic turns out to be correct/intended, it is not user-friendly nor intuitive. I've probably overwrote builds 5 times now, and it's fucking irritating every time, especially since there is no Undo for Save operations. Again if your logic is currently intended, please change it so that if you Save As a new build, you make that new saved build the currently selected build.

**Comment by EmmittJ** [comment]
This has never really been brought up. The save feature has worked the same
way since we picked up the app. The build highlighted is the 'current
build' even if it isn't the one loaded. I can look into a way to change it,
but it might not be very welcomed because of how long the app has had the
same save feature

**Comment by dsnvwlmnt** [comment]
Let me clarify. You have a random build loaded. You click reset, to create a new build. You make the build. You click Save As and save it under a new build name.

What i'm asking for, is that this new build *which is loaded visibly on your screen*, become the currently selected build (presumably when you click Save As).

It is nonsensical for the previous build you had loaded, to still be selected, which has no relation to the build you are currently looking at, which you just created, and which you saved under a new name.

**Comment by EmmittJ** [comment]
I completely understand the system you are asking for. You want a file like
system, like a word document, you 'open' a build and the changes you make
save to that build.

It does make sense for a build to be selected when it is a selectable menu.
Skill tree comparison is a feature that takes advantage of the 'build' you
have loaded and the current selected 'build' in the menu.

Currently, in the program, a 'build' is just a link that you save and your
actions don't affect this at all. I would like to point out that the
reverse situation could happen where someone would load a build and think
that, because of the old system, that selecting a build on the list would
overwrite that selected build.

You have to look at it from our view as well as yours. This is the first
time we have heard of a complaint about the save method of builds. We need
to look into overhauling the build system, which is currently one of the
longer issues we have, but I personally haven't had the time recently to do
much ground work within the app.

**Comment by l0g0sys** [comment]
I think there is easy fix, just force select build which was created by 
Save As.

**Comment by EmmittJ** [comment]
While it doesn't address the problem as a whole, it should be a simple fix
until we can improve the build system.

**Comment by MLanghof** [comment]
> You want a file like system, like a word document, you 'open' a build and the changes you make save to that build.

No, that's not actually what he's asking for. All he wants is exactly what l0g0sys suggested.

**Comment by EmmittJ** [comment]
Whoops, I completely read that wrong. You are correct.
