### ISSUE TITLE
[request]Screenshot Save as ...

### ISSUE THREAD

**Issue by Hixxie** [EmmittJ/PoESkillTree#234]
First, I don't know where the directory is that images are saved to. I've looked and can't find it under my documents, the program folder, application data, etc.

Second, users should be able to save file as (dialog window) to change the file type (jpg, png, bmp, etc) and the directory.

**Comment by brather1ng** [comment]
It is saved to your clipboard, you can open any image editing program (even Paint is enough) and press Ctrl+V and it should be pasted there.

But yes, removing the need to open a different program for saving screenshots would definetely help.

**Comment by Pecral** [comment]
I've added this now for jpg and png.

The problem is, if the user didn't select any node, there will be no file dialog at the moment.
Although this is intended, it could be a bit confusing if nothing happens after clicking a button - there should be a little information box at least.

You can ignore the first commit.. That's my first commit ever and I didn't know that a commit on a forked repository is automatically mentioned here.

**Comment by SpaceOgre** [comment]
@Pecral How do you feel about this? Is it in a state where others might use it? If so please do a pull-request.

**Comment by Pecral** [comment]
Sorry for the late response!
I've created a pull-request now.

**Comment by EmmittJ** [comment]
This has been added with #294
