### ISSUE TITLE
View tree comparaison : the program crashed

### ISSUE THREAD

**Issue by SamIsNotaDev** [EmmittJ/PoESkillTree#292]
Hello, version 2.2.5
When clicking on "View -> skill tree comparaison", the program crashed. I can't launch the program again (it crashes at startup, exception is different from #290 )

Local lang = french

[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/173778/debug.txt)

**Comment by brather1ng** [comment]
That happened to me once, too. But I couldn't reproduce it because I deleted the PersistentData.

To fix your program not being able launch you have to find your PersistentData.xml, find `<TreeComparisionEnabled>` and replace the `true` inside of `<TreeComparisonEnabled>...</TreeComparisonEnabled>` with `false`.

Would be nice if you could post the contents of that file before changing it. That would enable us to fix the bug.

**Comment by SamIsNotaDev** [comment]
Thanks for the reply, here is the file (with a .txt extension in order to be supported by github.

[PersistentData.txt](https://github.com/EmmittJ/PoESkillTree/files/173879/PersistentData.txt)

The workaround works.
