### ISSUE TITLE
Translation fitting Windows locale is used with no way to change it back

### ISSUE THREAD

**Issue by brather1ng** [EmmittJ/PoESkillTree#301]
If you use the portable version, the app uses the translation that fits the Windows locale. The problem is, there is no in-app way to change the language for people that rather want to use English. It would be a good idea to add the language to the settings menu.

Another minor issue: the installer doesn't show German as a possible language.

**Comment by SpaceOgre** [comment]
Yeah this would be a good idea. Add a language dropdown to the settings containing all languages in the Locale folder. During this it might be a good idea to add some kind of version compatibility to the translations, since some of the translations are old and might miss strings that where added later.

**Comment by EmmittJ** [comment]
Should be fairly easy. We just need to populate the list of locale data
then change the language setting in persistent data.

**Comment by SpaceOgre** [comment]
Added this just now, program restart is needed atm since I could not get the mainwindow to re-render with the new language only new windows used it. So if you have any ideas please have a look. In the meantime I added an prompt that informs the user that a restart is required.

**Comment by EmmittJ** [comment]
I think restarting is fine, and I think German hasn't been added to the
installer because I forgot to add it, but it should still be deployed.
On Apr 11, 2016 10:16 AM, "Daniel Mauritzson" <notifications@github.com>
wrote:

Added this just now, program restart is needed atm since I could not get
the mainwindow to re-render with the new language only new windows used it.
So if you have any ideas please have a look. In the meantime I added an
prompt that informs the user that a restart is required.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/301#issuecomment-208455213>

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/commit/b2415b8905fca00ee889ef84ed84158079b37c3c#

That commit shows how to add it to the installer. I won't be at a computer for some time. Also, @brather1ng would you like to be added as a contributor?

**Comment by brather1ng** [comment]
> @brather1ng would you like to be added as a contributor?

Sure, would be nice.

**Comment by EmmittJ** [comment]
Added :)

**Comment by brather1ng** [comment]
Thanks!

Thats what you meant. I thought you meant the "About - Authors" list. But yeah, I don't mind being a Collaborator either ;)

**Comment by EmmittJ** [comment]
We do need to update the authors list :p you can throw yourself on there
now

**Comment by EmmittJ** [comment]
Alright, this has been fixed with the last few commits
