### ISSUE TITLE
Passive Tree/Equipment Tabs

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#302]
I'm not a fan about of how the Passive Tree/Equipment Tabs looks/are placed. Does anyone have a suggestion on how they could be changed/moved?

On the one hand I get the sentiment behind it since they toggle what we see in the "Editor" area but I'm wondering how many are using the equipment tab and if it might not be better to move them to the menu instead. A part of this is also because the equipment stuff is not working 100% either.

**Comment by EmmittJ** [comment]
I do think it should be kept out, but they look pretty bad. I think fixing the equipment stuff would be a better solution then just sweeping it under the rug. 

I would like to add jewel crafting and such to this menu, so that we can add jewel support (at least rare/magic).

**Comment by MLanghof** [comment]
I've been wondering whether the project would be renamed in that case?

If we have full-on character designing, can you still call it "passive tree planner"?

**Comment by EmmittJ** [comment]
At this point is there really a reason to re-brand?
On Apr 12, 2016 4:04 PM, "Max Langhof" <notifications@github.com> wrote:

I've been wondering whether the project would be renamed in that case?

If we have full-on character designing, can you still call it "passive tree
planner"?

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/302#issuecomment-209141500>

**Comment by EmmittJ** [comment]
I know this topic got a bit derailed, but I have been thinking about it for a bit. I am not really sure what to do about equipment and the inventory stuff. On one hand I would like to fix it up, but it seems like it may be pretty hard to maintain. 

There is basically no automation on with the attributes gear has or even can have, and I don't see a reasonable way of doing so. We might be able to get something going with one of the ggpk reading api's, but I haven't had much time to look into PyPoE.

**Comment by brather1ng** [comment]
I have started fixing and updating it. I planned on doing a WIP Merge Request today or tomorrow so you can see what I already did and what I plan to do. For now, you can get an idea from the commits I did to my itemImprov-branch (here's a list: https://github.com/EmmittJ/PoESkillTree/compare/master...brather1ng:itemImprov), there are also a bunch of fixes I haven't yet commited.

For the base items I wrote a Wiki parser and for the possible affixes an exilemods parser. It's true that it needs maintaining when things change, but it's far less hardcoded stuff than what's done in Compute.cs.

**Comment by brather1ng** [comment]
To get back on topic:
![tabswitching](https://cloud.githubusercontent.com/assets/7596346/15693050/94fbd584-2792-11e6-89f2-a2f2c95a4983.PNG)
Looks much better, imo.

**Comment by EmmittJ** [comment]
Way better and slightly less dominant than previously. It allows the
passive tree to be the main focus with the equipment easily reachable

**Comment by SpaceOgre** [comment]
Looks great!

**Comment by l0g0sys** [comment]
Yep, better. Tho you should use "Skill Tree" term instead of "Passive 
Tree". That's what it's referenced as in help files and across the 
application.

Official term is "Passive Skill Tree", but we use "Skill Tree".

It's really hard to keep localization up-to-date or even write help 
files, if we aren't consistent in our terminology.
