### ISSUE TITLE
Redownload Skill Tree Assets: Progressbar not showing correctly

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#329]
When using the "Redownload Skill Tree Assets" function the progressbar is only shown for a small part of the whole duration instead of all of it, it just looks as if the app is frozen.

**Comment by brather1ng** [comment]
That whole progress window stuff does not run asynchronous at all. It will always freeze because the asset loading blocks the UI thread, which may sometimes get enough time to actually update the progress window.

Replacing our progress window by MahApps' ProgressDialog and doing it properly async is actually already on my todo list.

**Comment by SpaceOgre** [comment]
Okay, great :)

I leave this open in the meantime just for reference.
