### ISSUE TITLE
This is updated for Prophecy?

### ISSUE THREAD

**Issue by MortenHJ** [EmmittJ/PoESkillTree#333]
I just downloaded this from a link from the official PoE website, and it says it's an offline skill tree planner.

I'm a bit worried about security issues since after closing and opening the program again, it had updated its information on ascendency builds.

Before it showed the same information as pathofexile.gamepedia.com but now it's showing new information on the same skills.

I thought it was an offline skill tree planner. Then how did it update itself?

And besides that, is the new information here updated for Prophecy ladder and the 2.3 update? Because on the download info, it says it's for ascendency 2.2.10, and not 2.3.

**Comment by EmmittJ** [comment]
> I thought it was an offline skill tree planner. Then how did it update
itself?

It didn't update itself. It isn't possible.

> Before it showed the same information aspathofexile.gamepedia.com but now
it's showing new information on the same skills

I'm not sure what this is referring to.

> And besides that, is the new information here updated for Prophecy ladder
and the 2.3 update? Because on the download info, it says it's for
ascendency 2.2.10, and not 2.3.

The program version is 2.2.10. This isn't related to ascendancy at all. The
skill tree data is for 2.3 Prophecy league.

**Comment by MortenHJ** [comment]
Ok but ascendency trees just got updated in 2.3 that's what I'm curious.

Thanks for replying so quick.

**Comment by MLanghof** [comment]
It can update, but only if you go through Help -> Check for Updates...

It will never auto-update itself as you claimed.

**Comment by EmmittJ** [comment]
If you downloaded 2.2.10 then the tree would update. It is packaged with the install.
