### ISSUE TITLE
Request: Save tagged nodes with saved build and sharable tagged nodes

### ISSUE THREAD

**Issue by IGP** [EmmittJ/PoESkillTree#338]
Currently tagged nodes are not saved between runs. If you close the application then you lose whatever tagged nodes you had setup.

In addition tagged nodes are not linked to builds. If you are switching between builds and want to use the feature you need to open multiple instances of the program to accommodate them.

What I would like to see is the ability to save tagged nodes on a per build basis and have them persist across sessions. It would also be nice to be able to share tagged nodes for assistance and collaboration.

**Comment by brather1ng** [comment]
Making tagged nodes persistent and part of a build shouldn't be too hard and a good idea, imo (tagged nodes would disappear on switching builds, don't know if that clashes with someones use of that feature).

Sharing builds (and the tagged nodes with them) would be possible when builds are saved as individual files, see #192 for that.

**Comment by MLanghof** [comment]
I'm also in support of saving the taggings since they tend to be more important than the actual tree when you create builds with the associated tools (skill tagged nodes, tree generator). On the same note, saving tree generator settings (also as part of the build?) would be equally beneficial.

I agree that we'll need to revive the discussion about saving individual build files for this purpose, so discussions about the data format should probably happen in the linked issue.
