### ISSUE TITLE
Crafting Window

### ISSUE THREAD

**Issue by CassidyB** [EmmittJ/PoESkillTree#347]
Can you make the drop-downs for the crafting window respond to keyboard shortcuts or words?  Say that I type "mana" or "M" it would sort the list by the word "mana" and exclude other items or if I typed "m" it would select the first item starting with "M".

Just an idea.   Love your work.

**Comment by brather1ng** [comment]
Filtering those drop-down by checking if an entry contains the input field contents instead of if it begins with that is something I did already try at some point. It would be nice to have but seems to require to write a completely new control (all the solutions I found had problems).

Checking the input field for keywords or stuff like that isn't worth it imo as the drop-downs don't contain that much and it would require manually tagging all mods.

**Comment by EmmittJ** [comment]
It shouldn't be that hard to filter out a combobox. `IsEditable=True` and `IsTextSearchEnabled=True` should do the trick.

**Comment by brather1ng** [comment]
Just realized that I did this with #423
