### ISSUE TITLE
Time to do an pre-release?

### ISSUE THREAD

**Issue by SpaceOgre** [EmmittJ/PoESkillTree#382]
Do anyone have anything in the pipe? Otherwise I think it might be time to do a pre-release so that we can get some broader testing for the new save build structure.

**Comment by EmmittJ** [comment]
Yeah, I was planning on one tomorrow, or the day after.

On Sep 27, 2016 11:07 AM, "Daniel Mauritzson" <notifications@github.com>
wrote:

Do anyone have anything in the pipe? Otherwise I think it might be time to
do a pre-release so that we can get some broader testing for the new save
build structure.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/382>, or mute the thread

**Comment by EmmittJ** [comment]
Done
