### ISSUE TITLE
[Suggestion] Add Ascendency nodes tagging support for the Skill Tree Generator.

### ISSUE THREAD

**Issue by Tahj42** [EmmittJ/PoESkillTree#392]

**Comment by MLanghof** [comment]
We initially had this enabled, but removed it mainly due to technical reasons (iirc to disable the algorithm from going through scion ascendancy, ascendancy nodes are simply removed from the graph considered by the tree generator). 

What exactly do you need this for? There is a setting for whether or not "Reset" resets your ascendancy (Edit -> Settings -> at the bottom), so if you are annoyed that your ascendancy is reset every time you want to run the generator, you can change that there.

**Comment by brather1ng** [comment]
Closing this because of no further input and because I can't see value in it. If you have something to add, feel free to reopen this.
