### ISSUE TITLE
PseudeAttribute #% increased Evasion Rating and Iron Reflexes

### ISSUE THREAD

**Issue by EnderWiggin** [EmmittJ/PoESkillTree#416]
This pseudo attribute has dexterity bonus to evasion active even with iron reflexes selected.
Also, why iron reflexes add armor bonus to evasion rating pseudo attribute? Wouldn't it be better to add evasion to armor when iron reflexes selected?

**Comment by brather1ng** [comment]
Fixed your first point.

On the armor bonus: that's a tricky one, since these are only the increases, not the resulting armor/evasion values. Evasion increases should definitely not count towards armor increases with Iron Reflexes, as they only increase parts of your armor (that part that comes from evasion). The current way makes sense because your total evasion is increased by armor increases (and then converted to armor, which would be a reason to not include it).

**Comment by EmmittJ** [comment]
We actually used to include them together, but that is technically
incorrect and some people had pointed this out. They need to be two
separate stats based feedback and correctness.
