### ISSUE TITLE
The Program Crashed

### ISSUE THREAD

**Issue by dsnvwlmnt** [EmmittJ/PoESkillTree#417]
I installed it to a different folder than the default: C:\Program Files (x86)\PoESkillTree - Breach

Anytime i run PoESkillTree.exe, it crashes with this message: The program crashed. A stack trace can be found at: C:\Users\<myuser>\AppData\Roaming\PoESkillTree - Atlas of Worlds\debug.txt

Here is a paste of debug.txt: http://pastebin.com/Mc6Uxxwr

**Comment by brather1ng** [comment]
There seems to be an issue with your `PersistentData.xml`. Can you upload it? It is located in the same folder as the `debug.txt`.

**Comment by dsnvwlmnt** [comment]
http://pastebin.com/Bqf5Bs9e

**Comment by GitHub-devel** [comment]
Same issue and it is not problem with PersistentData.xml, since removing the file itself or just starting zip version doesn't do anything:
http://pastebin.com/ezcymPqH

**Comment by brather1ng** [comment]
@dsnvwlmnt Some of your builds where somehow saved with an empty level tag instead of level 0 or nor level tag. That can't be parsed as a number, which crashes the program.

If you replace your file with the following one it should work (it at least works for me, I have simply removed all empty level tags): http://pastebin.com/jn0cggms

I have no idea how those empty tags happened, but they are probably caused by a previous version, so we can't fix it anyway.

@GitHub-devel You first had the same issue, which you can solve by manually removing all `<Level />` occurences from your PersistentData file. Then it crashed because the PseudoAttributes folder is missing (`Data\PseudoAttributes`), you can copy the one from the zip.

**Comment by dsnvwlmnt** [comment]
I think the version update process could be vastly improved. I now find myself in a spaghetti of hardcoded folder paths or something.

How about assuming that when someone installs the new program, check whether they have the old one installed, and use the PersistentData.xml that already exists. Here it keeps overwriting it, and despite me making a new folder for settings files for Breach, it's partially using a hardcoded path to the old Ascendancy one.

It's a nightmare, and i can't figure out how to get my builds to load on the new version at all.

**Comment by brather1ng** [comment]
Using these specific folders per program is what AppData is for. If you want to have everything at a place of your choice, you can use the portable version.

> It's a nightmare, and i can't figure out how to get my builds to load on the new version at all.

Go to Edit -> Settings -> Buid save path -> Change and select the folder you want to store builds in.

> I've never understood why you have a differently named folder for each version in the first place, and is what causes the problems for long time users.

I think it was so people could still have access to old skill tree versions. I don't really understand it either.

**Comment by dsnvwlmnt** [comment]
The build save path thing is what i was trying to use and it doesn't work. I even got a crash when dancing around trying to get it to work.
