### ISSUE TITLE
Comparison builds colors

### ISSUE THREAD

**Issue by kimurin** [EmmittJ/PoESkillTree#428]
Here is 1st build: http://imgur.com/a/Y88Tk
Here is the comparison with the 2nd build: http://imgur.com/a/cmHhq (I opened 1st build and single click on second).

So in theory i should get **10 more Int (+10 green - gain color)** and **70 less Str (-70 red - lose color)**.

Lets open 2nd build: http://imgur.com/a/zUcwI
There are **10 LESS Int** and **70 MORE Str** instead. It's so confusing. This colors should be reversed.

**Comment by EmmittJ** [comment]
Your current build has 10 more int and 70 less str than the 2nd build. I'm
not too sure it matters how it is displayed as long as you know what
green/red means. We could probably do a better job with that.

**Comment by MLanghof** [comment]
You have opened build 1. You are comparing it with build 2 (build 1 is still opened).

It shows the stats of build 1 (because that's the opened build) and shows how it differs from build 2 (it has 70 less strength, hence a red -70).

You're thinking about it the wrong way around (and if we'd change it, other people would consider it inverted). The current solution makes sense if you think about it the way it's intended (you see how the current build differs from a second one).
