### ISSUE TITLE
Application out of memory

### ISSUE THREAD

**Issue by SyndromeDayna** [EmmittJ/PoESkillTree#459]
2 gigabytes of memory is not enough to generate a skill tree. I set the number of iterations to 20 and it crashed. I think you should compile an x64 executable.

I use so many iterations because when I set their number to 10, the application did not even manage to repeat my hand-made skill tree. I deleted the unnecessary attributes and rounded down the remaining ones, but it still used more skill points than I did.

**Comment by brather1ng** [comment]
This will be fixed in the next release, see #440. It doesn't really need that much memory.

For somewhat complex skill trees with many attributes, you can't expect it to always find the optimal solution (your hand-made skill tree probably is optimal with the attributes it has), even with lots of iterations. The solver simply isn't good enough for that.
