### ISSUE TITLE
Jewel Radius and Limit

### ISSUE THREAD

**Issue by EmmittJ** [EmmittJ/PoESkillTree#464]
Jewel Radius and Limit is not displayed on unique jewels. It seems as those stats aren't included in the `Uniques.xml` file even after running UpdateDB

http://pathofexile.gamepedia.com/Rapid_Expansion

http://i.imgur.com/hnNIna4.png

**Comment by brather1ng** [comment]
Properties are in the API under specific names (see http://pathofexile.gamepedia.com/Special:Browse/Rapid_Expansion "Has jewel radius"). They have to be handled explicitly. I simply didn't think about jewels when doing that.

**Comment by EmmittJ** [comment]
All good. It was just something I noticed, so I figured I would make an
issue.

**Comment by brather1ng** [comment]
Was actually slightly more work than I initially thought because properties were not supported for unique bases (only their base items). 

What you'll have to deal with is that crafted jewels' radius properties display numbers instead of the Small/Medium/Large of imported jewels. Our property crafting only supports numbers as values, so that is necessary. You'll probably want to convert the radius keywords of imported jewels to numbers anyway.
