### ISSUE TITLE
Missing stats for Equipment

### ISSUE THREAD

**Issue by justtocomplain** [EmmittJ/PoESkillTree#475]
No idea if it applies for other items, but latest release only allows crafted range values for certain mods on Bone helmets.

**Comment by MLanghof** [comment]
Can you give an example? There are some mods that can only be master-crafted on bone (or other int) helmets, like strength.

**Comment by brather1ng** [comment]
I only just saw your edit, so didn't look into it before.

There are two problems that cause this:

1. All atlas base types are missing the armour type tag (e.g. dex_armour or str_int_armour) in our data, so the normally rollable mods based on those tags can't be crafted. This is a bug in the Wiki, from which base types are exported. The tags are there in the game data.
2. All types of percent defense can be master crafted on items in game. However, all percent defense mods have the same group "DefencesPercent". Since our crafting uses that group for creating an affix and only distinguishes mods in one grouo by value, only one master crafted defense mod can be crafted. This mod happens to be the Armour and ES one. I'll simply throw all master crafted percent defense mods out. The normally rollable ones cover them anyway.

On the second slider for reflect: that mod for some reason has two stats. The first is the reflect, the second is "dummy_stat_display_nothing" with value 0. The second one should be hidden anyway, as there are no values to choose from.

**Comment by brather1ng** [comment]
Wiki data was fixed
