### ISSUE TITLE
Suboptimal steiner tree

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#480]
This one turns out to be 100% reproducible: http://imgur.com/XUN2Row
Or in copy-paste form: https://pastebin.com/x0ykS5Rj
Removing any one tagged node eliminates the suboptimal path.

I have looked into it and it turns out that everything gets collapsed into a single GraphNode (and thus the GA never gets to do anything) which is expanded in this sub-optimal fashion.

I couldn't easily find a rogue SteinerReduction in the time I spent, but while I can't rule out that there's a subtle error in there, I'm not actually sure whether it might not be the assumptions underlying the entire process: Does collapsing nodes into GraphNodes just mean "the optimal solution uses the shortest paths between these nodes" or does it actually mean "connecting these nodes via any shortest paths is guaranteed to be optimal"? Do we maybe have to instead build the MST of each GraphNode?

**Comment by brather1ng** [comment]
At least in theory our assumption is correct: the tests that can merge a node into another node specifically contract the edge between them, i.e. that edge is part of an optimal solution. There might be an issue with how edge contraction/node merging is handled, but I don't have the time to look further into it right now.

**Comment by brather1ng** [comment]
This is actually a relatively simple bug. I have no idea why it didn't cause problems before.

Quoting the relevant case of the DegreeTest: "Edges from one target node to another that are of minimum cost among the edges of  one of the nodes can be in any optimal solution. Therefore both target nodes can be merged."

The minimum distance from a node to any node is calculated and then all target nodes with that distance are merged into into it. The bug is that the minimum distance can obviously change by merging, only one merge should happen at a time.

With your example:

![degreetestbug](https://user-images.githubusercontent.com/7596346/27502023-529666da-5871-11e7-8872-6b0bfa96a112.png)
(nodes in one red area are one target GraphNode, the two marked pairs of nodes are the problematic ones)

The target in the middle was first merged with the one above and then with the one below as both are the minimum distance away. But after one merge, the minimum distance is lower and the second merge is not valid anymore.

**Comment by MLanghof** [comment]
> I have no idea why it didn't cause problems before.

I was similarly surprised when I managed to reproduce it. My guess is that it's rare for skill trees to be this "pathological"; most of the time this kind of merge would only cover connections that are optimal anyway. But it's hard to tell how much it did affect results in the wild.
